CREATE TABLE IF NOT EXISTS `global superstore`.`raw_data` (
  `Category` VARCHAR(255) NULL,
  `City` VARCHAR(255) NULL,
  `Country` VARCHAR(255) NULL,
  `raw_datacol` VARCHAR(45) NULL,
  `Customer ID` VARCHAR(45) NULL,
  `Customer Name` VARCHAR(255) NULL,
  `Discount` INT NULL,
  `Market` VARCHAR(45) NULL,
  `Number of records` INT NULL,
  `Order Date` VARCHAR(255) NULL,
  `Order ID` VARCHAR(255) NULL,
  `Order Priority` VARCHAR(255) NULL,
  `Product ID` VARCHAR(255) NULL,
  `Product Name` VARCHAR(255) NULL,
  `Profit` DECIMAL(10,4) NULL,
  `Quantity` INT NULL,
  `Region` VARCHAR(255) NULL,
  `Row ID` INT NULL,
  `Sales` INT NULL,
  `Segment` VARCHAR(255) NULL,
  `Ship Date` VARCHAR(255) NULL,
  `Ship Mode` VARCHAR(255) NULL,
  `Shipping Cost` DECIMAL(10,4) NULL,
  `State` VARCHAR(255) NULL,
  `Sub-Category` VARCHAR(255) NULL,
  `Year` YEAR NULL,
  `Market2` VARCHAR(255) NULL,
  `weeknum` INT NULL);
