CREATE TABLE IF NOT EXISTS `raw_data` (
  `Category` varchar(255) DEFAULT NULL,
  `City` varchar(255) DEFAULT NULL,
  `Country` varchar(255) DEFAULT NULL,
  `Customer ID` varchar(45) DEFAULT NULL,
  `Customer Name` varchar(255) DEFAULT NULL,
  `Discount` int DEFAULT NULL,
  `Market` varchar(45) DEFAULT NULL,
  `Number of records` int DEFAULT NULL,
  `Order Date` varchar(255) DEFAULT NULL,
  `Order ID` varchar(255) DEFAULT NULL,
  `Order Priority` varchar(255) DEFAULT NULL,
  `Product ID` varchar(255) DEFAULT NULL,
  `Product Name` varchar(255) DEFAULT NULL,
  `Profit` decimal(10,4) DEFAULT NULL,
  `Quantity` int DEFAULT NULL,
  `Region` varchar(255) DEFAULT NULL,
  `Row ID` int DEFAULT NULL,
  `Sales` int DEFAULT NULL,
  `Segment` varchar(255) DEFAULT NULL,
  `Ship Date` varchar(255) DEFAULT NULL,
  `Ship Mode` varchar(255) DEFAULT NULL,
  `Shipping Cost` decimal(10,4) DEFAULT NULL,
  `State` varchar(255) DEFAULT NULL,
  `Sub-Category` varchar(255) DEFAULT NULL,
  `Year` year DEFAULT NULL,
  `Market2` varchar(255) DEFAULT NULL,
  `weeknum` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;